=== inowas/inowas/spec/schema/modflow/command/updateBoundary.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "id": "https://inowas.com/schema/",
    "properties": {
        "uuid": {
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        },
        "message_name": {
            "type": "string",
            "pattern": "^updateBoundary$"
        },
        "metadata": {
            "type": "object"
        },
        "payload": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                },
                "boundary_id": {
                    "type": "string",
                    "pattern": "^[a-z0-9_\\-]{3,255}$"
                },
                "boundary": {
                    "$ref": "modflow/boundary/boundary.json"
                }
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "uuid",
        "message_name",
        "metadata",
        "payload"
    ]
}

=== inowas/inowas/tests/Inowas/Modflow/Schema/_files/createModflowModel.json
{
    "uuid": "ce849e4c-dfc8-4ab2-a37a-69f37088e771",
    "message_name": "createModflowModel",
    "metadata": {},
    "payload": {
        "id": "f3f6788a-61a6-410e-a14d-af7ecca6babb",
        "name": "NewModflowModel",
        "description": "NewModflowModelDescription",
        "geometry": {
            "type": "Polygon",
            "coordinates": [[[-5e6, -1e6], [-4e6, 1e6], [-3e6, -1e6], [-5e6, -1e6]]]
        },
        "bounding_box": [
            {"lng": 12.1, "lat": 1.0},
            {"lng": 12.8, "lat": 1.5}
        ],
        "grid_size": {
            "n_x": 50,
            "n_y": 60
        },
        "time_unit": 2,
        "length_unit": 2
    }
}
